import { FormData, ReportData } from '../types';

export const defaultFormData: FormData = {
  // Page 1 - Request Information
  isPart: false,
  isMaterial: false,
  materialCode: '',
  partMaterial: '',
  supplierCode: '',
  supplierName: '',
  shippedCargoType: '',
  isPrelaunch: false,
  isPrototype: false,
  site: '',
  dateSentToFactory: '',
  billOfLadingNo: '',
  quantity: '',
  reasonMaterialChange: false,
  reasonApprovalExpiry: false,
  reasonNewSupplier: false,
  reasonChangeDesign: false,
  reasonNewPart: false,
  reasonProcessChange: false,
  productTechnicalCode: '',
  productName: '',
  productStage: '',
  isMassProduction: false,
  isProductDevelopment: false,
  dataSheetNo: '',
  drawingNo: '',
  manufacturerSelectionNumber: '',
  requesterName: '',
  requesterPosition: '',
  requesterDateSignature: '',
  approverName: '',
  approverPosition: '',
  approverDateSignature: '',
  
  // Page 2 - Initial Review
  requestAcceptable: false,
  notAcceptable: false,
  notAcceptableDueTo: '',
  qaName1: '',
  qaPosition1: '',
  qaDateSignature1: '',
  noTestReport: false,
  noECR: false,
  qaName2: '',
  qaPosition2: '',
  qaDateSignature2: '',
  noSample: false,
  noPrototype: false,
  
  // Page 3 - Review Process
  dimensionalOK: false,
  dimensionalNOK: false,
  dimensionalEvidence: '',
  materialOK: false,
  materialNOK: false,
  materialEvidence: '',
  durabilityOK: false,
  durabilityNOK: false,
  durabilityEvidence: '',
  performanceOK: false,
  performanceNOK: false,
  performanceEvidence: '',
  assemblyOK: false,
  assemblyNOK: false,
  assemblyEvidence: '',
  documentsOK: false,
  documentsNOK: false,
  documentsEvidence: '',
  samplesOK: false,
  samplesNOK: false,
  samplesEvidence: '',
  betterThan: false,
  worseThan: false,
  sameAs: false,
  noParallel: false,
  comparisonEvidence: '',
  expertName1: '',
  expertPosition1: '',
  expertDateSignature1: '',
  managerName1: '',
  managerPosition1: '',
  managerDateSignature1: '',
  isGeneral: true,
  isExclusive: false,
  documentCode: '',
  
  // Page 4 - Additional fields
  durabilityOKP4: false,
  durabilityNOKP4: false,
  durabilityEvidenceP4: '',
  performanceOKP4: false,
  performanceNOKP4: false,
  performanceEvidenceP4: '',
  assemblyOKP4: false,
  assemblyNOKP4: false,
  assemblyEvidenceP4: '',
  documentsOKP4: false,
  documentsNOKP4: false,
  documentsEvidenceP4: '',
  samplesOKP4: false,
  samplesNOKP4: false,
  samplesEvidenceP4: '',
  betterThanP4: false,
  worseThanP4: false,
  sameAsP4: false,
  noParallelP4: false,
  comparisonEvidenceP4: '',
  expertName2: '',
  expertPosition2: '',
  expertDateSignature2: '',
  managerName2: '',
  managerPosition2: '',
  managerDateSignature2: '',
  
  // Page 5 - QA and Management
  qaExpertName: '',
  qaExpertPosition: '',
  qaExpertDateSignature: '',
  qaManagerName: '',
  qaManagerPosition: '',
  qaManagerDateSignature: '',
  isApproved: false,
  isConditionallyApproved: false,
  isApprovedLimited: false,
  isRejected: false,
  approvalDescription: '',
  approvalUntilDate: '',
  deputyName: '',
  deputyPosition: '',
  deputyDateSignature: '',
  prelaunchNeeded: false,
  prelaunchNotNeeded: false,
  auditNeeded: false,
  auditNotNeeded: false,
  
  // Page 6 - Final Registration
  archiveDate: '',
  evidence: '',
  actions: '',
  finalName: '',
  finalPosition: '',
  finalDateSignature: '',
  isGeneralP6: true,
  isExclusiveP6: false,
  documentCodeP6: ''
};

export const initialReportsData: ReportData[] = [
  // Test report with reviewer remarks for Edit functionality
  {
    id: "test-edit-1",
    requestId: "REQ-EDIT-001",
    fileName: "Engineering_Approval_Form.xlsx", // Matches the template with parsedSections
    uploadDate: "2026-01-20",
    assignedTo: "Test User",
    department: "engineering",
    status: "needs-revision",
    lastModified: "2026-01-24 10:30",
    fileSize: "1.8 MB",
    documentType: "Request",
    product: "Test Product",
    site: "Test Site",
    uploadedBy: "admin",
    fromUser: "admin", // Set to current user so it shows in Remarks Inbox
    formData: {
      field_part_name: "Hydraulic Pump Assembly",
      field_part_number: "HP-2024-001",
      field_manufacturer: "TechParts Inc.",
      field_supplier: "Global Supply Co.",
      field_description: "High-pressure hydraulic pump for industrial applications",
      field_material: "Stainless Steel 316",
      field_dimensions: "150mm x 200mm x 180mm",
      field_weight: "5.2",
      field_standard: "ISO 9001",
      field_requested_by: "John Engineering",
      field_request_date: "2026-01-20"
    },
    returnedBy: "reviewer",
    returnedByName: "Jane Reviewer",
    returnedDate: "2026-01-24",
    remarks: "Please update the supplier certification section with the latest ISO standards. Also, the delivery timeline needs to be more specific - provide exact dates instead of 'Q1 2026'. Finally, add contact information for the quality manager at the supplier location."
  },
  // Test report with approver remarks for Edit functionality
  {
    id: "test-edit-2",
    requestId: "REQ-EDIT-002",
    fileName: "Quality_Inspection_Form.xlsx", // Matches the template with parsedSections
    uploadDate: "2026-01-22",
    assignedTo: "Test User",
    department: "quality",
    status: "needs-revision",
    lastModified: "2026-01-25 14:45",
    fileSize: "2.1 MB",
    documentType: "Request",
    product: "Quality Test",
    site: "QA Lab",
    uploadedBy: "admin",
    fromUser: "admin", // Set to current user so it shows in Remarks Inbox
    formData: {
      field_inspector: "Sarah Quality",
      field_inspection_date: "2026-01-22",
      field_batch_number: "BATCH-2026-042",
      field_quantity: "500",
      field_appearance: "Good condition",
      field_color: "As specified"
    },
    returnedBy: "approver",
    returnedByName: "Robert Approver",
    returnedDate: "2026-01-25",
    remarks: "The budget justification is insufficient. Please provide a detailed cost-benefit analysis including ROI projections for the next 3 years. Additionally, the environmental impact assessment is missing - this is mandatory for all supplier approvals."
  },
  {
    id: "1",
    requestId: "REQ001",
    fileName: "Supplier_Approval_Form_001.xlsx",
    uploadDate: "2025-12-08",
    assignedTo: "John Smith",
    department: "supply-chain",
    status: "submitted",
    lastModified: "2025-12-08 14:30",
    fileSize: "2.3 MB",
    documentType: "Request",
    product: "Industrial Pumps",
    site: "Manufacturing Plant A",
    uploadedBy: "admin",
    fromUser: "John Doe",
    formData: defaultFormData,
    aiWorkflow: [
      {
        id: "wf-1",
        department: "procurement",
        departmentName: "Procurement",
        order: 1,
        status: "completed",
        assignedTo: "Sarah Chen",
        completedDate: "2024-01-16 10:00",
        stages: [
          {
            id: "stage-1",
            name: "Vendor Information",
            status: "completed",
            assignedTo: "Sarah Chen",
            completedDate: "2024-01-15 16:00"
          },
          {
            id: "stage-2",
            name: "Purchase Request Details",
            status: "completed",
            assignedTo: "Sarah Chen",
            completedDate: "2024-01-16 10:00"
          }
        ]
      },
      {
        id: "wf-2",
        department: "quality-assurance",
        departmentName: "Quality Assurance",
        order: 2,
        status: "current",
        assignedTo: "Mike Williams",
        stages: [
          {
            id: "stage-3",
            name: "Quality Standards",
            status: "completed",
            assignedTo: "Mike Williams",
            completedDate: "2024-01-17 09:00"
          },
          {
            id: "stage-4",
            name: "Inspection Criteria",
            status: "current",
            assignedTo: "Mike Williams"
          },
          {
            id: "stage-5",
            name: "Certification Requirements",
            status: "pending"
          }
        ]
      },
      {
        id: "wf-3",
        department: "operations",
        departmentName: "Operations",
        order: 3,
        status: "pending",
        stages: [
          {
            id: "stage-6",
            name: "Delivery Requirements",
            status: "pending"
          },
          {
            id: "stage-7",
            name: "Logistics Planning",
            status: "pending"
          }
        ]
      },
      {
        id: "wf-4",
        department: "management",
        departmentName: "Management",
        order: 4,
        status: "pending",
        stages: [
          {
            id: "stage-8",
            name: "Final Management Approval",
            status: "pending"
          }
        ]
      }
    ]
  },
  {
    id: "2",
    requestId: "REQ002",
    fileName: "Material_Approval_Form_002.xlsx",
    uploadDate: "2025-12-05",
    assignedTo: "Sarah Johnson",
    department: "finance",
    status: "initial-review",
    lastModified: "2025-12-05 09:15",
    fileSize: "1.8 MB",
    documentType: "Request",
    product: "Steel Components",
    site: "Factory B",
    uploadedBy: "requestor",
    fromUser: "Sarah Johnson",
    formData: defaultFormData
  },
  {
    id: "3",
    requestId: "REQ003",
    fileName: "Part_Manufacturer_Form_003.xlsx",
    uploadDate: "2025-12-07",
    assignedTo: "Mike Davis",
    department: "operations",
    status: "approved",
    lastModified: "2025-12-07 16:45",
    fileSize: "3.1 MB",
    documentType: "Request",
    product: "Electrical Parts",
    site: "Manufacturing Plant A",
    uploadedBy: "requestor",
    fromUser: "Mike Davis",
    preparedBy: "Mike Davis",
    approvedDate: "2025-12-07",
    documentId: "DOC-OPS-2025-003",
    documentTitle: "Electrical Parts Manufacturer Approval",
    formData: defaultFormData
  },
  {
    id: "4",
    requestId: "REQ004",
    fileName: "Quality_Approval_Form_004.xlsx",
    uploadDate: "2025-12-02",
    assignedTo: "Emily Wilson",
    department: "quality-assurance",
    status: "review-process",
    lastModified: "2025-12-02 11:20",
    fileSize: "2.7 MB",
    documentType: "Request",
    product: "Quality Tools",
    site: "QA Lab",
    uploadedBy: "requestor",
    fromUser: "Emily Wilson",
    formData: defaultFormData
  },
  {
    id: "5",
    requestId: "REQ005",
    fileName: "Procurement_Form_005.xlsx",
    uploadDate: "2025-11-28",
    assignedTo: "Robert Brown",
    department: "procurement",
    status: "final-review",
    lastModified: "2025-11-28 13:30",
    fileSize: "2.0 MB",
    documentType: "Request",
    product: "Raw Materials",
    site: "Warehouse C",
    uploadedBy: "requestor",
    fromUser: "Robert Brown",
    formData: defaultFormData
  },
  {
    id: "6",
    requestId: "REQ006",
    fileName: "Engineering_Approval_006.xlsx",
    uploadDate: "2025-11-15",
    assignedTo: "Lisa Anderson",
    department: "engineering",
    status: "supplier-sample",
    lastModified: "2025-11-15 15:10",
    fileSize: "2.9 MB",
    documentType: "Request",
    product: "Engineering Parts",
    site: "R&D Center",
    uploadedBy: "requestor",
    fromUser: "Lisa Anderson",
    formData: defaultFormData
  },
  {
    id: "7",
    requestId: "REQ007",
    fileName: "Manufacturing_Form_007.xlsx",
    uploadDate: "2025-10-10",
    assignedTo: "David Martinez",
    department: "manufacturing",
    status: "pending",
    lastModified: "2025-10-10 10:45",
    fileSize: "1.6 MB",
    documentType: "Request",
    product: "Manufacturing Tools",
    site: "Production Line 1",
    uploadedBy: "requestor",
    fromUser: "David Martinez",
    formData: defaultFormData
  },
  {
    id: "8",
    requestId: "REQ008",
    fileName: "Supplier_Review_008.xlsx",
    uploadDate: "2025-09-05",
    assignedTo: "Jennifer Garcia",
    department: "supply-chain",
    status: "rejected",
    lastModified: "2025-09-05 12:15",
    fileSize: "2.4 MB",
    documentType: "Request",
    product: "Supply Chain Items",
    site: "Distribution Center",
    uploadedBy: "requestor",
    fromUser: "Jennifer Garcia",
    formData: defaultFormData
  },
  {
    id: "9",
    requestId: "REQ009",
    fileName: "New_Part_Request_009.xlsx",
    uploadDate: "2026-01-25",
    assignedTo: "Robert Taylor",
    department: "engineering",
    status: "submitted",
    lastModified: "2026-01-25 09:30",
    fileSize: "1.9 MB",
    documentType: "Request",
    product: "Mechanical Parts",
    site: "Engineering Lab",
    uploadedBy: "requestor",
    fromUser: "Alice Cooper",
    formData: defaultFormData
  },
  {
    id: "10",
    requestId: "REQ010",
    fileName: "Material_Change_Request_010.xlsx",
    uploadDate: "2026-01-24",
    assignedTo: "Robert Taylor",
    department: "quality-assurance",
    status: "submitted",
    lastModified: "2026-01-24 16:00",
    fileSize: "2.1 MB",
    documentType: "Request",
    product: "Composite Materials",
    site: "QA Testing Center",
    uploadedBy: "requestor",
    fromUser: "Mark Wilson",
    formData: defaultFormData
  },
  // Approved documents for Document Publishing
  {
    id: "11",
    requestId: "REQ011",
    fileName: "Supplier_Approval_Hydraulics.xlsx",
    uploadDate: "2026-01-10",
    assignedTo: "Sarah Chen",
    department: "supply-chain",
    status: "approved",
    lastModified: "2026-01-20 14:30",
    fileSize: "2.5 MB",
    documentType: "Request",
    product: "Hydraulic Systems",
    site: "Manufacturing Plant A",
    uploadedBy: "preparator",
    fromUser: "Sarah Chen",
    preparedBy: "Sarah Chen",
    approvedDate: "2026-01-20",
    documentId: "DOC-SC-2026-011",
    documentTitle: "Hydraulic Systems Supplier Approval",
    formData: defaultFormData
  },
  {
    id: "12",
    requestId: "REQ012",
    fileName: "Quality_Standards_Electronics.xlsx",
    uploadDate: "2026-01-12",
    assignedTo: "Mike Williams",
    department: "quality-assurance",
    status: "approved",
    lastModified: "2026-01-22 11:15",
    fileSize: "3.2 MB",
    documentType: "Request",
    product: "Electronic Components",
    site: "QA Lab",
    uploadedBy: "preparator",
    fromUser: "Mike Williams",
    preparedBy: "Mike Williams",
    approvedDate: "2026-01-22",
    documentId: "DOC-QA-2026-012",
    documentTitle: "Electronic Components Quality Standards",
    formData: defaultFormData
  },
  {
    id: "13",
    requestId: "REQ013",
    fileName: "Manufacturing_Process_Motors.xlsx",
    uploadDate: "2026-01-08",
    assignedTo: "David Martinez",
    department: "manufacturing",
    status: "approved",
    lastModified: "2026-01-18 16:00",
    fileSize: "2.8 MB",
    documentType: "Request",
    product: "Electric Motors",
    site: "Production Line 2",
    uploadedBy: "preparator",
    fromUser: "David Martinez",
    preparedBy: "David Martinez",
    approvedDate: "2026-01-18",
    documentId: "DOC-MFG-2026-013",
    documentTitle: "Electric Motors Manufacturing Process",
    formData: defaultFormData
  },
  {
    id: "14",
    requestId: "REQ014",
    fileName: "Engineering_Specs_Sensors.xlsx",
    uploadDate: "2026-01-15",
    assignedTo: "Lisa Anderson",
    department: "engineering",
    status: "approved",
    lastModified: "2026-01-23 09:45",
    fileSize: "2.1 MB",
    documentType: "Request",
    product: "Temperature Sensors",
    site: "R&D Center",
    uploadedBy: "preparator",
    fromUser: "Lisa Anderson",
    preparedBy: "Lisa Anderson",
    approvedDate: "2026-01-23",
    documentId: "DOC-ENG-2026-014",
    documentTitle: "Temperature Sensors Engineering Specifications",
    formData: defaultFormData
  },
  {
    id: "15",
    requestId: "REQ015",
    fileName: "Procurement_Agreement_Materials.xlsx",
    uploadDate: "2026-01-05",
    assignedTo: "Robert Brown",
    department: "procurement",
    status: "approved",
    lastModified: "2026-01-19 13:20",
    fileSize: "3.5 MB",
    documentType: "Request",
    product: "Raw Materials Package",
    site: "Warehouse C",
    uploadedBy: "preparator",
    fromUser: "Robert Brown",
    preparedBy: "Robert Brown",
    approvedDate: "2026-01-19",
    documentId: "DOC-PROC-2026-015",
    documentTitle: "Raw Materials Procurement Agreement",
    formData: defaultFormData
  },
  {
    id: "16",
    requestId: "REQ016",
    fileName: "Finance_Budget_Approval.xlsx",
    uploadDate: "2026-01-14",
    assignedTo: "Sarah Johnson",
    department: "finance",
    status: "approved",
    lastModified: "2026-01-21 10:30",
    fileSize: "1.9 MB",
    documentType: "Request",
    product: "Budget Allocation Q1",
    site: "Finance Department",
    uploadedBy: "preparator",
    fromUser: "Sarah Johnson",
    preparedBy: "Sarah Johnson",
    approvedDate: "2026-01-21",
    documentId: "DOC-FIN-2026-016",
    documentTitle: "Q1 2026 Budget Allocation Approval",
    formData: defaultFormData
  },
  {
    id: "17",
    requestId: "REQ017",
    fileName: "Operations_Workflow_Optimization.xlsx",
    uploadDate: "2026-01-11",
    assignedTo: "Mike Davis",
    department: "operations",
    status: "approved",
    lastModified: "2026-01-24 15:00",
    fileSize: "2.6 MB",
    documentType: "Request",
    product: "Workflow System",
    site: "Operations Center",
    uploadedBy: "preparator",
    fromUser: "Mike Davis",
    preparedBy: "Mike Davis",
    approvedDate: "2026-01-24",
    documentId: "DOC-OPS-2026-017",
    documentTitle: "Operations Workflow Optimization Plan",
    formData: defaultFormData
  },
  {
    id: "18",
    requestId: "REQ018",
    fileName: "Supplier_Contract_Plastics.xlsx",
    uploadDate: "2026-01-13",
    assignedTo: "Jennifer Garcia",
    department: "supply-chain",
    status: "approved",
    lastModified: "2026-01-25 12:00",
    fileSize: "3.0 MB",
    documentType: "Request",
    product: "Plastic Components",
    site: "Distribution Center",
    uploadedBy: "preparator",
    fromUser: "Jennifer Garcia",
    preparedBy: "Jennifer Garcia",
    approvedDate: "2026-01-25",
    documentId: "DOC-SC-2026-018",
    documentTitle: "Plastic Components Supplier Contract",
    formData: defaultFormData
  }
];